#!/usr/bin/env bash

set -e

echo "-----> [Sorbet Example Project] Nuking and regenerating Mocktail RBI files"
rm -rf sorbet/rbi/gems/mocktail*
bin/tapioca gems

echo "-----> [Sorbet Example Project] Type-checking"
bundle exec srb tc

echo "-----> [Sorbet Example Project] Running tests"
bundle exec rake
