#!/usr/bin/env bash

set -e

echo "-----> Running Mocktail's test against src"
COVER=true bundle exec rake

echo "-----> Building src/mocktail into lib/mocktail and lib/mocktail/sorbet"
./script/build

echo "-----> Running Mocktail's test against src"
MOCKTAIL_TEST_SRC_DIRECTORY="lib" bundle exec rake

echo "-----> Running Mocktail's test against src"
MOCKTAIL_TEST_SRC_DIRECTORY="lib/mocktail/sorbet" bundle exec rake

echo "-----> Type-checking Mocktail itself"
bundle exec srb tc

./script/test_sorbet_example
