#!/usr/bin/env bash

set -e

echo "-----> Running Mocktail's tests"
bundle exec rake

echo "-----> Type-checking Mocktail itself"
bundle exec srb tc

echo "-----> Verifying Sorbet type-checking works"
./script/test_sorbet_example
