require_relative "value/cabinet"
require_relative "value/call"
require_relative "value/demo_config"
require_relative "value/double"
require_relative "value/matcher_registry"
require_relative "value/stubbing"
