source "https://rubygems.org"

gem "mocktail", path: "../..", require: "mocktail/sorbet"

gem "standard"
gem "standard-sorbet"
gem "minitest", "~> 5.26" # 6.0+ requires Ruby >= 3.2, dropping support for Ruby 3.1
gem "rake"
gem "m"

gem "sorbet"
gem "sorbet-runtime"
gem "tapioca"
